{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.material",
    "module": "material",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "u5s42f2ocrek3aory3ujfa6zgq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.2.0.aar",
          "url": "material-1.2.0.aar",
          "size": 1231907,
          "sha512": "fb248aebe8d27d1bd70e30f0b165a45d738cc0226440c9633b3dd048895b8d0f504d9950ab791bb0e254af1d4fc109522033c92c48012fd40143ff352a02f8ec",
          "sha256": "558500623df50c69d564ec4f9632f4c2e1855ab210c3fa49d30daeb002edb2a8",
          "sha1": "3616de9b511a911fe2fd712ced289f7fe97de052",
          "md5": "9a2426b04ad7c1e56c76d3289efc28e4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.2.0.aar",
          "url": "material-1.2.0.aar",
          "size": 1231907,
          "sha512": "fb248aebe8d27d1bd70e30f0b165a45d738cc0226440c9633b3dd048895b8d0f504d9950ab791bb0e254af1d4fc109522033c92c48012fd40143ff352a02f8ec",
          "sha256": "558500623df50c69d564ec4f9632f4c2e1855ab210c3fa49d30daeb002edb2a8",
          "sha1": "3616de9b511a911fe2fd712ced289f7fe97de052",
          "md5": "9a2426b04ad7c1e56c76d3289efc28e4"
        }
      ]
    }
  ]
}
